### ISSUE TITLE
Selma Test doesn't clear keymap

### ISSUE THREAD

**Issue by 13r0ck** [pop-os/keyboard-configurator#114]
On a Lemu7 (The one that the production team uses), the Selma test doesn't clear the keymap when running. It does on a Oryp5 though.

The Selma test still seems to work even without clearing the keymap though. So maybe we should skip that step?

**Comment by jacobgkau** [comment]
Wasn't this intentional, from https://github.com/pop-os/keyboard-configurator/pull/109?

**Comment by 13r0ck** [comment]
Ah yes, production isn't on that PR.

But that will fix their issue when they get it, so I will close this issue.
