### ISSUE TITLE
`Fn` button toggle

### ISSUE THREAD

**Issue by NukeManDan** [pop-os/keyboard-configurator#143]
I see layer two mappings that I could _manually_ change behavior of for `F*` keys to map instead to change the behavior to have then do system control functions, but there is no way to toggle `Fn lock` that I can see.... is this possible?

Ideally I could use a sequence to toggle the layer1 and layer2 behavior, or more explicitly only the function keys (on a System76 `gaze17-3060b`) .

**Comment by crawfxrd** [comment]
Duplicate of #159
