### ISSUE TITLE
Feature request: support for FN lock key in System76 Open EC

### ISSUE THREAD

**Issue by leviport** [pop-os/keyboard-configurator#159]
Since https://github.com/system76/ec/pull/263/ is looking pretty good, it would be good to expose the key in system76-keyboard-configurator so users can map it once EC versions with the feature start making their way around.

**Comment by leviport** [comment]
Now that I think about it, exposing the Fn Lock button before EC supports it might be asking for trouble. I wonder if there's a way to conditionally show it based on the EC's release date.

**Comment by ids1024** [comment]
Yeah. Adding a keycode is trivial but we probably want it to only appear of firmware versions supporting it.

Parsing the date is probably good enough if not theoretically ideal. The only case that would be an issue is if someone checks out and compiles an older EC firmware.

**Comment by crawfxrd** [comment]
Firmware 2023-08-01_ec529da and newer has support for a FnLock key.

**Comment by vbatts** [comment]
update just landed on my `lemp9` and works like a charm. Thanks, all
