### ISSUE TITLE
Software does not detect Launch on macOS 13.3

### ISSUE THREAD

**Issue by ahoneybun** [pop-os/keyboard-configurator#168]
Tested keyboard-configurator 1.3.1 on lab Mac Mini with macOS 13.3, the keyboard works normally outside of this issue.

**Comment by ahoneybun** [comment]
I have three reports of this behavior with customers and it even happens with version 1.2.0 and 1.3.0 of the Keyboard Configurator.

**Comment by tavasolireza** [comment]
I have the same issue.

**Comment by patrickbeam** [comment]
I have the same issue on macOS version 13.3.1

**Comment by RickFoland** [comment]
I also have this issue on 13.3.1 and I'm not sure if this is fixed by PR #171. I pulled he repo and built it with `cargo run --release` but it still doesn't detect the Launch.

**Comment by leviport** [comment]
You could check that branch out and try building again

**Comment by RickFoland** [comment]
Ah, yeah. I built it from that branch and it does fix the issue.
