### ISSUE TITLE
`åäöøñňáàíčřšçžťþďæłāõôœ`

### ISSUE THREAD

**Issue by leukimi** [pop-os/keyboard-configurator#215]
How is your customer with system76 Launch totally customizable and fully reprogrammable open source mechanical keyboard supposed to write/type a special character `åäöøñňáàíčřšçžťþďæłāõôœ` on a latest version Linux Mint operating system?

DEB and RPM packages called `system76-keyboard-configurator` seems to exist for:

- Debian Sid (also called Debian Unstable)
- Ubuntu 23.04
- Ubuntu 22.04
- Fedora 38
- Fedora 37
- Archlinux
- Manjaro

See for instance [software.opensuse.org](software.opensuse.org)

See [AUR repository](https://aur.archlinux.org) for Archlinux and Manjaro.

See Fedora repositories.

See [pkgs.org](pkgs.org).

**Comment by jackpot51** [comment]
These special characters do not come from the keyboard's scancode mapping but from the operating system's layout. Different layouts will have these in different locations, I recommend you do research on keyboard layouts that your operating system provides.

**Comment by jackpot51** [comment]
For more clarity: at the keyboard level, you can map the A scancode to any key, but whether it outputs a, A, å, ä, á, or à is up entirely to the operating system and there is nothing the keyboard can do to control it.
