### ISSUE TITLE
v1.3.9 source code not compiling on Debian 12

### ISSUE THREAD

**Issue by leukimi** [pop-os/keyboard-configurator#216]
Maybe it should be pointed out (in release notes and on build instructions) for users who build from rust source that the v1.3.9 release requires minimum rustc version 1.64. Check with:

`rustc --version`

Debian 12 uses rustc version 1.63 and therefore does not compile rust source code. For Debian 12, the user has to use the appimage version.

Ubuntu 22.04 uses rustc version 1.66. 

v1.3.9 also compiles on Linux Mint 21.2 .

**Comment by crawfxrd** [comment]
If you want to use the Debian packages, you can checkout 1.3.7 which is before the gtk-rs update to 0.17. But better for building from source is to use rustup managed toolchains.

We can set [`rust-version`](https://doc.rust-lang.org/cargo/reference/manifest.html#the-rust-version-field) to indicate the MSRV.

**Comment by crawfxrd** [comment]
MSRV is now set to 1.64. You will receive an error that your compiler is too old.

Additional info:

- [Rust - Debian Wiki](https://wiki.debian.org/Rust)
- [ITP: rustup -- the rust toolchain installer](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1026333)
