### ISSUE TITLE
Add Cyrillic letters

### ISSUE THREAD

**Issue by spertulo97** [pop-os/keyboard-configurator#229]
I see that the Configurator now has a Russian translation, but it still can't configure Cyrillic layouts.
Without them, the program is useless for many users.
Please add Cyrillic letter support to the program.

**Comment by leviport** [comment]
Language configuration is out-of-scope for the Keyboard Configurator. Languages should be set in your OS, not in the keyboard's firmware. Keyboard firmware is only capable of [being mapped to keycodes](https://docs.qmk.fm/#/keycodes) of which there aren't enough to be used for internationalization.
