### ISSUE TITLE
Launch not respecting settings

### ISSUE THREAD

**Issue by stockphrase** [pop-os/keyboard-configurator#230]
I'm noticing that the keyboard will occasionally decide to change settings by itself and begin lighting up, even though I have it set for disabled. I have to remove the USB cord from the keyboard, plug it in, and then use the configurator to return to disabled. 

I should also note this behavior: when I notice that the lights have returned, I go into the configurator and try to use the software to alter the settings. The keyboard does not respond to any change requests. The only option is to unplug/replug.

**Comment by leviport** [comment]
Which version of Launch do you have? The configurator should say it above the layout when Launch is plugged in.

**Comment by stockphrase** [comment]
launch_3

**Comment by stockphrase** [comment]
Try this. 

Hit keys `FN + Esc`. The keyboard will no longer accept any settings and the LEDs do whatever they want. I suppose this is supposed to be Layer 2, reset. But after this the keyboard will not accept other settings. 

Since this is very close to hitting `Super + Esc`, which is what I use to lock my computer while I'm away, things can get annoying fast.

**Comment by leviport** [comment]
Ah I think I know what is going on. Are you seeing the letters "U N L O C K E D" light up in sequence? That Reset key is for firmware updates. Left ctrl + right ctrl + Esc should do the same thing, if you just want to remove that mapping on L2.

**Comment by stockphrase** [comment]
I moved the offending key...thanks.

**Comment by leviport** [comment]
No problem!
