### ISSUE TITLE
Gracefully handle Layers on Gaze15

### ISSUE THREAD

**Issue by bflanagin** [pop-os/keyboard-configurator#32]
system76-keyboard-configurator:
```
  Installed: 0.1.0~1618590925~21.04~217ce09
  Candidate: 0.1.0~1618590925~21.04~217ce09
  Version table:
 *** 0.1.0~1618590925~21.04~217ce09 1002
       1002 http://apt.pop-os.org/staging/keyboard-configurator hirsute/main amd64 Packages
        100 /var/lib/dpkg/status
```
On my gaze15 the keyboard shows that it has two layers. Switching to layer 2 cause the software to crash.

[INFO ] Adding LPC EC
thread 'main' panicked at 'index out of bounds: the len is 1 but the index is 1', src/application/backlight.rs:338:22
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by ids1024** [comment]
This should be fixed by dd9e452d826408fc71061c4b3e770c996445e49e.
