### ISSUE TITLE
Windows msi missing needed directories

### ISSUE THREAD

**Issue by bflanagin** [pop-os/keyboard-configurator#35]
Window msi fails to install the lib and share directories causing keyboard-configurator to fail.
Adding these two folders fixes the issue.

**Comment by ids1024** [comment]
With https://github.com/pop-os/keyboard-configurator/commit/1e3696b590a44dbd375992c468721242e43c59b6, it should include the `lib` and `share` directories. Hopefully it is behaving correctly now (Windows Installer is unintuitive and complicated)...

**Comment by bflanagin** [comment]
All good msi is now building.
