### ISSUE TITLE
foo release branches

### ISSUE THREAD

**Issue by claviger-pc** [pop-os/keyboard-configurator#41]
Making foo release branches sends out emails to those who are following this repo.  But we are excited to see that there is movement forward on your keyboard release.

**Comment by ids1024** [comment]
Ah, I suppose that would happen. I guess if I need to too much more testing of the release CI I'll do that on a fork (though that's a pain to do).

**Comment by ids1024** [comment]
No one what my fork. Nothing interesting is happening there. :laughing:
