### ISSUE TITLE
Lemp9 default keymap is incorrect on right hand side.

### ISSUE THREAD

**Issue by bflanagin** [pop-os/keyboard-configurator#45]
Several of the keys on both layer 1 and layer 2 are incorrectly mapped on the default layout for the lemp9. I've added a modified layout based on my keyboard ([lemp9_default.zip](https://github.com/pop-os/keyboard-configurator/files/6468010/lemp9_default.zip).) I set the un-mappable keys (ones we don't have actions for) to "none"

### Layer 1
Current:
![lemp9-righthandkeys-butwrong](https://user-images.githubusercontent.com/10382037/118017643-7a76e300-b31c-11eb-9f7e-3f88a96d81d4.png) 
Fixed:
![lemp9-righthandkeys-layer1-corrected](https://user-images.githubusercontent.com/10382037/118017894-bf9b1500-b31c-11eb-848f-342f09e56a3b.png)
Note: The key set to "none" is the Pause/Break button on the physical keyboard

### Layer 2
Current:
![lemp9-righthandkeys-layer2-butwrong](https://user-images.githubusercontent.com/10382037/118018042-e6594b80-b31c-11eb-92d4-0e27bd682ab9.png)
Fixed:
![Lemp9-righthandkeys-layer2-corrected](https://user-images.githubusercontent.com/10382037/118018061-eb1dff80-b31c-11eb-8df1-1529ccd7a37e.png)
Note: The key set to "none" is the Pause/Break button on the physical keyboard, and Del/Screen Lock

**Comment by ids1024** [comment]
Hm, the default layout the Configurator uses is automatically generated from https://github.com/system76/ec/blob/master/src/board/system76/lemp9/keymap/default.c, and seems to correctly match that.

**Comment by bflanagin** [comment]
That is odd, could my keyboard be different than other lemp9s?
![IMG_20210512_130809_436](https://user-images.githubusercontent.com/10382037/118024604-7ea6fe80-b324-11eb-9e1c-5ace2de4a163.jpg)

**Comment by leviport** [comment]
Oh that's right! Your lemp9 has the preprod keyboard. Dangit, I'm sorry I didn't remember that.

**Comment by bflanagin** [comment]
Ah, sorry Ian false alarm.
