### ISSUE TITLE
Icon not being used at all times in Wayland

### ISSUE THREAD

**Issue by ahoneybun** [pop-os/keyboard-configurator#47]
It seems that on GNOME 40 on Wayland the icon is not used in the Overview or in the Dock though it does show up in the App Search just fine. I believe something is missing from the `.desktop` file so I'm looking at what icons are working and their `.desktop` files to compare.

Here is a screenshot showing the issue:

![Screenshot from 2021-05-13 13-39-40](https://user-images.githubusercontent.com/4884946/118178218-ed518e00-b3f0-11eb-8179-762eb67d6f9a.png)

**Comment by ahoneybun** [comment]
It looks like the Firmware Manager file is like this:

[Desktop Entry]
Type=Application
Name=Firmware Manager
Icon=firmware-manager
Comment=Manage system and device firmware
Categories=System;GTK
Keywords="firmware;system76;fwupd;lvfs;"
StartupNotify=true
Exec=/usr/bin/com.system76.FirmwareManager

So maybe we're missing StartupNotify=true

**Comment by ids1024** [comment]
I think https://github.com/pop-os/keyboard-configurator/commit/000969ba983deee3d50d4ab061313b02989075ab might fix this.

`StartupNotify=true` seems to be unrelated, but correct for anything using `GtkApplication`, so I've added that as well.

**Comment by ahoneybun** [comment]
Looks like that fixed it! Just built from master:

![Screenshot from 2021-05-20 11-05-52](https://user-images.githubusercontent.com/4884946/119020397-6a35b800-b95b-11eb-9b9e-f06eab764714.png)

**Comment by ahoneybun** [comment]
It also fixed the icon in the AppMenu in the top left when the application is focused.

**Comment by ids1024** [comment]
Great!
