### ISSUE TITLE
Bug: Unplugging Launch while configuring doesn't hide layer selector or deactivate Import/Export/Reset layout menu items

### ISSUE THREAD

**Issue by leviport** [pop-os/keyboard-configurator#54]
If I unplug my Launch while I'm in the "Configure layout" section, I am returned to the keyboard selection screen where my oryp6 keyboard is shown along with (if I plug it back in) my Launch. However, the layer selector at the top of the window is not hidden like it is if I hit the "back" arrow in the top left corner instead. The Import/Export/Reset Layout menu items are also not changed to an inactive state like they are if I use the "back" button. 

![2021-05-21_10-38](https://user-images.githubusercontent.com/13512097/119170875-18effc00-ba21-11eb-8122-15194fb5b2ad.png)

**Comment by ids1024** [comment]
Fixed in https://github.com/pop-os/keyboard-configurator/commit/285dd530bfc119612f0ff20b622222bc5a4469fc.
