### ISSUE TITLE
Ability to map System Power Key

### ISSUE THREAD

**Issue by isantop** [pop-os/keyboard-configurator#94]
It would be nice to be able to map the System Power key. QMK handles this with `KC_POWER`. It's treated identically to if the user presses the power button on their PC.

On Pop_OS in the default configuration, this present the system prompt to shut down:

![image](https://user-images.githubusercontent.com/5883565/134413981-248fc7e0-fd71-42b5-8f64-648dbb75c370.png)

**Comment by ahoneybun** [comment]
This was fixed in commit a472e198d1b2b74abb77fae14db51d9d811ac858
